apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - nginx.yaml
  - jetstack.yaml
  - metallb.yaml
  - nfs-subdir.yaml
  - external-secrets.yaml
  - redpanda.yaml
  - oauth2-proxy.yaml
  - onepassword.yaml