apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sources
- cert-manager
- oauth2-proxy
- nginx
#- postgress
- metallb
- nfs-provisioner
- external-secrets
#- onepassword-connect
#- redpanda